### ISSUE TITLE
"EasySync" has been deprecated in regards to "CSync" 2.0.0 version

### ISSUE THREAD

**Issue by Fl4sHNoX** [tpatall/ExtendMouthDogSlide#1]
Just wanted to give a heads-up as CSync is still currently a dependency for [ExtendMouthDogSlide](https://github.com/tpatall/ExtendMouthDogSlide)

As stated on [EasySync](https://github.com/Dreadrith/LC_EasySync?tab=readme-ov-file#notice)'s GitHub page:

> CSync is now able to fulfill the same purpose EasySync was made for so it is now archived.

cf. [CSync Dependency & "2.0.0" Update
](https://github.com/Dreadrith/LC_EasySync/issues/2#issue-2156772206)

**Comment by tpatall** [comment]
Thanks for taking the time to notify people about the change!
